//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call_Audit_Center
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallAuditCenterEntities : DbContext
    {
        public CallAuditCenterEntities()
            : base("name=CallAuditCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Call_Details> Call_Details { get; set; }
        public virtual DbSet<Call_Scoring_Details> Call_Scoring_Details { get; set; }
        public virtual DbSet<Question_Details> Question_Details { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<Login_Details> Login_Details { get; set; }
    }
}
