//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call_Audit_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Call_Details()
        {
            this.Call_Scoring_Details = new HashSet<Call_Scoring_Details>();
        }
    
        public long Call_ID { get; set; }
        public string Agent_Name { get; set; }
        public Nullable<int> Agent_ID { get; set; }
        public Nullable<System.DateTime> Call_DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Call_Scoring_Details> Call_Scoring_Details { get; set; }
    }
}
